name: create-release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'The bump in version for this release'
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  create-release:
    uses: TwelveIterationMods/Workflows/.github/workflows/create-release.yml@main
    with:
      bump: ${{ github.event.inputs.bump }}
    secrets: inherit
